### ISSUE TITLE
List Group Schedules returning error 404

### ISSUE THREAD

**Issue by spencermcm** [cronhooks/forum#10]
Hi, I triple checked my code and can not get the end point for listing group schedules to work. I'm getting a 404 error. Is this a bug?

The group ID and API key is correct, just blocked out for this post.

Here is the code I'm using:

[
    {
        "ca": null,
        "qs": [],
        "url": "https://api.cronhooks.io/groups/GROUP-ID/schedules?skip=0&limit=10",
        "gzip": true,
        "method": "get",
        "headers": [
            {
                "name": "Content-Type",
                "value": "application/json"
            },
            {
                "name": "Authorization",
                "value": "Bearer key_BLOCKED-FOR-PRIVACY"
            }
        ],
        "timeout": null,
        "useMtls": false,
        "authPass": null,
        "authUser": null,
        "bodyType": null,
        "serializeUrl": false,
        "shareCookies": false,
        "parseResponse": true,
        "followRedirect": true,
        "useQuerystring": false,
        "followAllRedirects": false,
        "rejectUnauthorized": true
    }
]

**Comment by mrameezraja** [comment]
Hi @spencermcm ,

You should be able to access this endpoint. There was a permission issue with your account.

Please let me know if issue is resolved.

Thanks,
Rameez
