### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by heymartinadams** [cronhooks/forum#16]
On this [page](https://docs.cronhooks.io/#retrieve-a-scheduled-webhook), seeing what I think is a discrepancy between `schedule id` and result. Should these two `id` be the same?

![CleanShot 2022-09-19 at 12 35 10@2x](https://user-images.githubusercontent.com/11673745/191100846-120f4e64-4ba2-49d2-9755-0905662e734f.png)

**Comment by mrameezraja** [comment]
Hi @heymartinadams ,

Yes, you are right. Id's should be same and they are now. Thanks for pointing that out.
