### ISSUE TITLE
No response for NextJS/Vercel webhook

### ISSUE THREAD

**Issue by heymartinadams** [cronhooks/forum#17]
For some reason the webhook doesn’t get a response, and I have no idea why.

Using NextJS on Vercel, I have this code:

```js
// Packages
import crypto from 'crypto'
import { buffer } from 'micro'

export const config = { api: { bodyParser: false } }

const PagesApiRoute = async (req, res) => {
  const cronhooksSignature = req.headers['Cronhooks-Signature']

  if (!cronhooksSignature) return res.status(400).send()

  const rawBody = await buffer(req)

  const body = rawBody.toString()

  const expectedSignature = crypto
    .createHmac('sha256', process.env.CHRONHOOKS_WEBHOOK)
    .update(body)
    .digest('hex')

  if (cronhooksSignature !== expectedSignature) return res.status(400).send()

  return res.status(200).send()
}

export default PagesApiRoute
```

My dashboard is showing this:

<img width="1105" alt="CleanShot 2022-09-19 at 21 33 10@2x" src="https://user-images.githubusercontent.com/11673745/191168214-f384ecd9-2092-4754-ad10-e2842fc11c15.png">

**Comment by mrameezraja** [comment]
Hi @heymartinadams ,

So you are returning 400 response at two places:

``` if (!cronhooksSignature) return res.status(400).send()```
``` if (cronhooksSignature !== expectedSignature) return res.status(400).send()```

You might change 400 to 401 at this line
``` if (cronhooksSignature !== expectedSignature) return res.status(*401*).send() ``` 

So in this case we will know at which point exactly function is failing.

**Comment by heymartinadams** [comment]
Thank you, @mrameezraja. Tried that, but still received a `400 Bad Request` status. What I find curious is that even custom logging (e.g. `console.log(req.headers)`) doesn’t show up when the webhook is triggered (although the logs show that the webhook itself is triggered).

**Comment by heymartinadams** [comment]
Are we supposed to include `Cronhooks-Signature` into headers on our end (if yes, how)? Or is this done automatically by cronhooks?

**Comment by mrameezraja** [comment]
@heymartinadams first of all console.log won't show up, only the returns. So let's do step by step debugging. 
First return cronhooksSignature then see the trigger logs.
then return body 
then the expectedSignature and cronhooksSignature.

**Comment by mrameezraja** [comment]
signature is computed and added to request headers automatically.

**Comment by heymartinadams** [comment]
Thank you, @mrameezraja 🎉 That methodical approach did the trick: 1. changing the error code, and 2. returning the variables in order to log output.

I discovered that there’s no `req.headers['Cronhooks-Signature']`, but only `req.headers['cronhooks-signature']`! 🤦🏻‍♂😭

So many hours wasted on this little mistake.

Thank you so much again for your help (and saving me many more hours)!

Below, the correct code for anyone wishing to use Cronhooks with NextJS/Vercel:

```js
// Packages
import crypto from 'crypto'
import { buffer } from 'micro'

export const config = { api: { bodyParser: false } }

const PagesApiRoute = async (req, res) => {
  const cronhooksSignature = req.headers['cronhooks-signature']

  if (!cronhooksSignature) return res.status(400).send()

  const rawBody = await buffer(req)

  let body = rawBody.toString()

  const expectedSignature = crypto
    .createHmac('sha256', process.env.CHRONHOOKS_WEBHOOK)
    .update(body)
    .digest('hex')

  if (cronhooksSignature !== expectedSignature) return res.status(400).send()

  // Parse the body *after* the signature comparison in order to access its properties ← this one took me hours to figure out 😆 
  body = JSON.parse(body)

  // Do your thing...
  const webhookName = body.cronhooks.Title // etc.
  // ...

  return res.status(200).send()
}

export default PagesApiRoute
```

**Comment by heymartinadams** [comment]
ps: @mrameezraja Feel free to use the above code for a blog post targeting NextJS/Vercel users. Tested and works. 🙂
