### ISSUE TITLE
Variables support

### ISSUE THREAD

**Issue by jdrydn** [cronhooks/forum#18]
It would be great to see variables support on Cronhooks, so I could build webhooks pointing to my service but easily change URLs or secret keys without editing every single webhook I've configured 😬 

![Screenshot 2022-10-24 at 10 26 32](https://user-images.githubusercontent.com/406967/197495275-bad8c335-8156-40eb-b65c-b6f98b1aa2e4.jpg)

I imagine variables should be supported in:

- URL
- Headers (key and/or value)
- Payload

**Comment by mrameezraja** [comment]
Hi @jdrydn , your suggestion is well received! Will keep you posted. Thanks

**Comment by mrameezraja** [comment]
Hi @jdrydn ,

Your requested feature is deployed. Please play around and let us know!

**Global Variables:**
![image](https://user-images.githubusercontent.com/8121938/198884169-afa6295a-8a1b-4d14-ac02-493decb7d682.png)

**Group Variables:**
![FgPsQ_5WQAsdH_d](https://user-images.githubusercontent.com/8121938/198883979-73acd267-bebf-4528-8446-9ebaa2194418.jpeg)

**Usage:**
![image](https://user-images.githubusercontent.com/8121938/198884136-44194e74-c6cf-4b4c-9197-a2136113fe81.png)


Thanks,
Rameez

**Comment by jdrydn** [comment]
Nice!! Incredible turnaround, really appreciate it @mrameezraja 🚀 And you've also included support in the Cronhooks API 🤘So far working really well, thanks!
