### ISSUE TITLE
Allowing the triggering, editing and deletion of a scheduled cronhook from the details page

### ISSUE THREAD

**Issue by calum-bird** [cronhooks/forum#2]
It may be helpful (just as a quality of life improvement) to allow users to trigger, edit, or delete scheduled cronhooks from their respective details page. This is explicitly an enhancement, and only saves a couple clicks, but would be very nice from a user experience perspective.

Great work so far!

**Comment by mrameezraja** [comment]
Yes Calum, that feature is already in my to do list.

**Comment by calum-bird** [comment]
Great, can't wait to see it!

**Comment by mrameezraja** [comment]
Hi Calum, 
Your requsted feature is deployed. Now you will be able to trigger/edit/delete a webhook from details page.

Thanks for your feedback. Keep it coming.

![image](https://user-images.githubusercontent.com/8121938/81301166-bfbd6080-9089-11ea-8030-4e47efa5ad0d.png)
