### ISSUE TITLE
How to duplicate my cron tasks?

### ISSUE THREAD

**Issue by sambuev** [cronhooks/forum#3]
Hello, I use webhooks for my script, in my case, it's time-consuming to set up 10 webhooks and then I need to duplicate to apply other Webhook URL, is it possible to get either get TWO webhooks URLs or duplicate existing Cron-Task and apply the other URL, please help me, otherwise I have to repeat my job just to add another webhook URL, please help!

**Comment by mrameezraja** [comment]
Hey Sam,

I will update you with the progress of your requested feature.

**Comment by sambuev** [comment]
Okay I will wait for it, when you can release it? I checking it every day!

**Comment by mrameezraja** [comment]
I have started working on it. It will be released possibly by end of this week.

**Comment by mrameezraja** [comment]
Hey @sambuev ,
Your requested feature is deployed.  Now you will be able to duplicate schedules. :)

![image](https://user-images.githubusercontent.com/8121938/84388696-10cef000-ac06-11ea-9764-b2a3d953074c.png)

**Comment by sambuev** [comment]
AMAZING! So great! 
I going to start using it now! Thank you so much, it's great improvement!
