### ISSUE TITLE
How to fire to two webhooks from one schedule?

### ISSUE THREAD

**Issue by sambuev** [cronhooks/forum#6]
Hello, I want to fire the same data to two webhooks at the same time, would be great if I can have a Plus + icon where I can input the second webhook address. Would save me a lot of time. Can you please make it?

**Comment by mrameezraja** [comment]
Hi @sambuev ,
As of now you can do two things to achieve:
1. Create a clone of schedule 
![image](https://user-images.githubusercontent.com/8121938/100486192-6ba8c500-311c-11eb-8354-c2447dfee109.png)

2. Call second webhook within your code of scheduled webhook

As of implementation, even if i do this from backend it will be a separate schedule as it is a different url. But i will consider this for future. I hope clone will do fine or second option is much better alternative.

Thanks,

**Comment by sambuev** [comment]
but I have to do it all the time, I already have dozen of webhooks, it would be easier if I can add another webhook URL inside the existing schedule

**Comment by mrameezraja** [comment]
i will see what can i do to ease your workload.

**Comment by sambuev** [comment]
Please 🙏

**Comment by sambuev** [comment]
Is there any update?

**Comment by mrameezraja** [comment]
Hey @sambuev ,

Your feature request is in progress.
![image](https://user-images.githubusercontent.com/8121938/107338803-69c49000-6ad5-11eb-91f7-3c3fc2a506e0.png)

**Comment by mrameezraja** [comment]
Hi @sambuev ,

Your feature is deployed. Play around and let me know.
![image](https://user-images.githubusercontent.com/8121938/107619083-0e78d600-6c6c-11eb-8cd9-1dc8705ef90f.png)

Thanks,

**Comment by sambuev** [comment]
Thank you so much! It will greatly help me a lot! I will start to use it!

**Comment by sambuev** [comment]
The option to add URL has been disappered, what happened? I do not see this once I editing my existing cronhooks

**Comment by sambuev** [comment]
Please add it to the existing hooks, I have all of them configured, but they are missing ADD-URL option.

**Comment by mrameezraja** [comment]
Hey @sambuev ,

It is not possible at the moment because each webhook is a separate schedule. It was added in new schedule for convenience.
