### ISSUE TITLE
API improvement to groups: list of webhooks IN a group

### ISSUE THREAD

**Issue by mikey186** [cronhooks/forum#8]
I saw the API changes now with the groups support now added. However, it only shows just the group...itself. I would wish to see the list of webhooks IN a group. Hope this comes in the near future.

**Comment by mrameezraja** [comment]
Hi @mikey186 ,

Now you can get webhooks in a group. Here are the docs. https://cronhooks.io/docs/#list-group-schedules

Thanks,
