### ISSUE TITLE
List Schedules Endpoint just returns "Ungrouped" Schedules

### ISSUE THREAD

**Issue by Techflow-ai** [cronhooks/forum#9]
API Endpoint:
GET https://api.cronhooks.io/schedules?skip=0&limit=10

Is this endpoint supposed to retrieve grouped and ungrouped schedules? (ALL schedules like in the description)
That's what I assumed but from testing it turned out that this endpoint just returns ungrouped schedules.

**Comment by mrameezraja** [comment]
Hi,

Yes you are right. This endpoint should return all schedules. Will get back to you once fixed and deployed.

Thanks,

**Comment by Techflow-ai** [comment]
Thank you so much for your superfast response!
Highly appreciated and will recommend cronhooks further.

**Comment by mrameezraja** [comment]
Hi @Techflow-ai ,

Fix is deployed. Can you please check and confirm.

Thanks,

**Comment by Techflow-ai** [comment]
Thank you very much!
Just checked it and it's working perfectly fine now. 
Appreciate your fast help.
